# tomcat
server:
    port: 8080
    servlet:
        context-path: /examination

spring:
    # thymeleaf
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false

    # mysql数据库
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/examination?userSSL=false
        username: examination
        password: 123123

 # 分页插件
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: countSql
# 打印SQL语句
#logging:
#    level:
#        cn.ksling.examination.mapper: debug
